on:
  push:
    paths:
      - "**.cs"
      - "**.csproj"
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write

env:
  version: "2.0.0.0"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Write environment to files
        shell: cmd
        run: |
          chcp 65001
          echo.[assembly: System.Reflection.AssemblyInformationalVersion("${{env.version}}+${{github.sha}}#${{github.run_number}}")]>src/Shared/AssemblyInformationalVersionAttribute.cs

      - name: Publish the solution
        run: ./src/Scripts/publish.bat

      # Serein.Lite
      - name: Upload binary files(Serein.Lite_win-x64)
        uses: actions/upload-artifact@v3
        with:
          name: Serein.Lite_win-x64
          path: ./src/Serein.Lite/bin/Debug/net6.0-windows/win-x64/publish

      # Serein.Plus
      - name: Upload binary files(Serein.Plus_win-x64)
        uses: actions/upload-artifact@v3
        with:
          name: Serein.Plus_win-x64
          path: ./src/Serein.Plus/bin/Debug/net6.0-windows10.0.18362/win-x64/publish

      # Serein.Cli
      - name: Upload binary files(Serein.Cli_win-x64)
        uses: actions/upload-artifact@v3
        with:
          name: Serein.Cli_win-x64
          path: ./src/Serein.Cli/bin/Debug/net6.0-windows/win-x64/publish

      - name: Upload binary files(Serein.Cli_linux-x64)
        uses: actions/upload-artifact@v3
        with:
          name: Serein.Cli_linux-x64
          path: ./src/Serein.Cli/bin/Debug/net6.0/linux-x64/publish

      - name: Upload binary files(Serein.Cli_linux-arm)
        uses: actions/upload-artifact@v3
        with:
          name: Serein.Cli_linux-arm
          path: ./src/Serein.Cli/bin/Debug/net6.0/linux-arm/publish

      - name: Upload binary files(Serein.Cli_linux-arm64)
        uses: actions/upload-artifact@v3
        with:
          name: Serein.Cli_linux-arm64
          path: ./src/Serein.Cli/bin/Debug/net6.0/linux-arm64/publish

      - name: Upload binary files(Serein.Cli_osx-x64)
        uses: actions/upload-artifact@v3
        with:
          name: Serein.Cli_osx-x64
          path: ./src/Serein.Cli/bin/Debug/net6.0/osx-x64/publish

      - name: Upload binary files(Serein.Cli_osx-arm64)
        uses: actions/upload-artifact@v3
        with:
          name: Serein.Cli_osx-arm64
          path: ./src/Serein.Cli/bin/Debug/net6.0/osx-arm64/publish

  attest-build-provenance:
    needs: [ build ]
    runs-on: windows-latest
    if: github.event_name == 'push'
   
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: downloads
      
      - shell: powershell
        run: | 
          del ./**/*.pdb
          tree /f
        
      # - uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-path:
  