on:
  push:
    paths:
      - "**.yml"
      - "**.cs"
      - "**.csproj"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          repo: SereinDev/Web
          workflow_conclusion: success
          path: src/Sources/
          skip_unpack: true
          if_no_artifact_found: warn

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish the solution
        run: ./src/Scripts/publish.bat

      # Serein.Gui
      - name: Upload binary files(Serein.Gui_win-x64)
        uses: actions/upload-artifact@v4
        with:
          name: Serein.Gui_win-x64
          path: ./src/Serein.Gui/bin/Release/net8.0-windows/win-x64/publish

      # Serein.Console
      - name: Upload binary files(Serein.Console_win-x64)
        uses: actions/upload-artifact@v4
        with:
          name: Serein.Console_win-x64
          path: ./src/Serein.Console/bin/Release/net8.0/win-x64/publish

      - name: Upload binary files(Serein.Console_linux-x64)
        uses: actions/upload-artifact@v4
        with:
          name: Serein.Console_linux-x64
          path: ./src/Serein.Console/bin/Release/net8.0/linux-x64/publish

      - name: Upload binary files(Serein.Console_linux-arm)
        uses: actions/upload-artifact@v4
        with:
          name: Serein.Console_linux-arm
          path: ./src/Serein.Console/bin/Release/net8.0/linux-arm/publish

      - name: Upload binary files(Serein.Console_linux-arm64)
        uses: actions/upload-artifact@v4
        with:
          name: Serein.Console_linux-arm64
          path: ./src/Serein.Console/bin/Release/net8.0/linux-arm64/publish

      - name: Upload binary files(Serein.Console_osx-x64)
        uses: actions/upload-artifact@v4
        with:
          name: Serein.Console_osx-x64
          path: ./src/Serein.Console/bin/Release/net8.0/osx-x64/publish

      - name: Upload binary files(Serein.Console_osx-arm64)
        uses: actions/upload-artifact@v4
        with:
          name: Serein.Console_osx-arm64
          path: ./src/Serein.Console/bin/Release/net8.0/osx-arm64/publish
