on:
  push:
    paths:
      - "**.cs"
  pull_request:
    paths:
      - "**.cs"
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run tests
        if: github.event_name == 'pull_request'
        run: 
          dotnet test src/Serein.Tests --logger GitHubActions

      - name: Generate coverage
        id: coverage
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          dotnet tool install --global JetBrains.dotCover.CommandLineTools
          dotCover cover-dotnet --Output=AppCoverageReport.xml --ReportType=DetailedXML -- test --logger GitHubActions -p:EnableWindowsTargeting=true

      - name: Run codacy-coverage-reporter
        if: steps.coverage.conclusion != 'skipped' && (failure() || success()) && matrix.os == 'windows-latest'
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: AppCoverageReport.xml

